// <auto-generated />
using System;
using System.Collections.Generic;
using AutoMarket.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoMarket.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831131642_AgregarPlanGratisYFlujoVendedor")]
    partial class AgregarPlanGratisYFlujoVendedor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoMarket.Core.Entities.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Accesorios")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("ColorExterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorInterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Combustible")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsDestacado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaDestacadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoGratisUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("DOP");

                    b.Property<string>("Motor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PrecioAnterior")
                        .HasColumnType("numeric");

                    b.Property<bool>("PublicarAlGuardar")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Traccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Transmision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Vistas")
                        .HasColumnType("integer");

                    b.Property<string>("_fotos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Fotos");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Marca");

                    b.HasIndex("Modelo");

                    b.HasIndex("TipoVehiculo");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Vistas");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Cupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Dias")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaximoUsos")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("UsosActuales")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Cupones_Codigo");

                    b.ToTable("Cupones");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.CuponRedencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuponId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PerfilDealerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDealerId");

                    b.HasIndex("CuponId", "PerfilDealerId")
                        .IsUnique()
                        .HasDatabaseName("IX_CuponesRedencion_Cupon_PerfilDealer");

                    b.ToTable("RedencionesCupon");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Encuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.EncuestaPregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EncuestaId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId", "Orden");

                    b.ToTable("EncuestasPreguntas");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.EncuestaRespuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EncuestaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ValorEscala")
                        .HasColumnType("integer");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EncuestaId", "UsuarioId");

                    b.HasIndex("EncuestaId", "UsuarioId", "PreguntaId")
                        .IsUnique()
                        .HasDatabaseName("IX_EncuestasRespuestas_Unicas");

                    b.ToTable("EncuestasRespuestas");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.HistorialVista", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VistoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "AnuncioId");

                    b.HasIndex("AnuncioId");

                    b.ToTable("HistorialVistas");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<string>("EmailContacto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NombreContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UsuarioIdRemitente")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.PagoSuscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaptureIdPayPal")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Ciclo")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("EventoIdPayPal")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("OrderIdPayPal")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PerfilDealerId")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("PerfilDealerId")
                        .HasDatabaseName("IX_PagosSuscripcion_PerfilDealerId");

                    b.ToTable("PagosSuscripcion");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.PerfilDealer", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("AgenciaRNC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Horarios")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("NombreAgencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TelefonoAgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.ToTable("PerfilesDealers");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.PlanCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CuotaDestacados")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("DescuentoAnualPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DescuentoTrimestralPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("DiasVigencia")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteAnuncios")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFotos")
                        .HasColumnType("integer");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioMensual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nivel")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanesCatalogo_Nivel");

                    b.ToTable("PlanesCatalogo");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.ReporteAnuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpReportante")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer");

                    b.Property<int?>("ResueltoPorAdminId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("Estado", "FechaCreacionUtc");

                    b.ToTable("ReportesAnuncios", (string)null);
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.SuscripcionDealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ciclo")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRecordatorioEnviadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimientoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilDealerId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlanCatalogoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilDealerId")
                        .IsUnique();

                    b.HasIndex("PlanCatalogoId");

                    b.HasIndex("FechaVencimientoUtc", "Estado")
                        .HasDatabaseName("IX_SuscripcionDealer_Vencimiento_Estado");

                    b.ToTable("SuscripcionDealers");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Estado", "Prioridad")
                        .HasDatabaseName("IX_Tickets_Estado_Prioridad");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.TicketMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMensajes");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("BloqueadoHastaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CodigoConfirmacionEmailExpiracionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodigoConfirmacionEmailHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CodigoConfirmacionExpiracionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodigoConfirmacionHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CodigoPasswordExpiracionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodigoPasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CodigoRecuperacionExpiracionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodigoRecuperacionHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailPendiente")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("EmailsEnviadosHoy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordPendienteHash")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoPersonal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TerminosAceptadosUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoEnvioCambioEmailUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoEnvioCambioPasswordUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoEnvioConfirmacionCuentaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoEnvioRecuperacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VentanaEmailsInicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.UsuarioFavorito", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("AnuncioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAgregadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsuarioId", "AnuncioId");

                    b.HasIndex("AnuncioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Anuncio", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithMany("Anuncios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.CuponRedencion", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Cupon", "Cupon")
                        .WithMany("Redenciones")
                        .HasForeignKey("CuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.PerfilDealer", "PerfilDealer")
                        .WithMany()
                        .HasForeignKey("PerfilDealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("PerfilDealer");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.EncuestaPregunta", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Encuesta", "Encuesta")
                        .WithMany("Preguntas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.EncuestaRespuesta", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Encuesta", "Encuesta")
                        .WithMany()
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.EncuestaPregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encuesta");

                    b.Navigation("Pregunta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.HistorialVista", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Lead", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Anuncio", "Anuncio")
                        .WithMany("Leads")
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.PagoSuscripcion", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.PerfilDealer", "PerfilDealer")
                        .WithMany()
                        .HasForeignKey("PerfilDealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilDealer");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.PerfilDealer", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithOne("PerfilDealer")
                        .HasForeignKey("AutoMarket.Core.Entities.PerfilDealer", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.ReporteAnuncio", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.SuscripcionDealer", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.PerfilDealer", "PerfilDealer")
                        .WithOne("Suscripcion")
                        .HasForeignKey("AutoMarket.Core.Entities.SuscripcionDealer", "PerfilDealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.PlanCatalogo", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanCatalogoId");

                    b.Navigation("PerfilDealer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Ticket", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.TicketMensaje", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.Ticket", "Ticket")
                        .WithMany("Mensajes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.UsuarioFavorito", b =>
                {
                    b.HasOne("AutoMarket.Core.Entities.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoMarket.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anuncio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Anuncio", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Cupon", b =>
                {
                    b.Navigation("Redenciones");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Encuesta", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.EncuestaPregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.PerfilDealer", b =>
                {
                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Ticket", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("AutoMarket.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("PerfilDealer");
                });
#pragma warning restore 612, 618
        }
    }
}
